/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModoEdicion;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static Interfaces.Inicio.opcionSimulacion;

/**
 *
 * @author JORGE OSORIO
 */
public class VistaSeleccionModoSimulacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaSeleccionModoSimulacion
     */
    public VistaSeleccionModoSimulacion() {
        initComponents();
        this.Configuraciones();
    }

    private void Configuraciones() {
        this.setTitle("MODO ELECCION");
        this.setAlwaysOnTop(true);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/Icono.png")).getImage());
    }

    public void OpcionSeleccionada() {

        if (this.btnMBatallas.isSelected()) {
            opcionSimulacion = 1;
        } else if (this.btnMRutaHorasNav.isSelected()) {
            opcionSimulacion = 2;
        } else if (this.btnMRutasGanacias.isSelected()) {
            opcionSimulacion = 3;
        } else if (this.btnRecorrerTodo.isSelected()) {
            opcionSimulacion = 4;
        } else if (this.btnRmasCorta.isSelected()) {
            opcionSimulacion = 5;
        } else if (this.btnRmasCostosa.isSelected()) {
            opcionSimulacion = 6;
        } else {
            opcionSimulacion = 7;
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton7 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelVistaSeleccion1 = new ModoEdicion.PanelVistaSeleccion();
        jLabel1 = new javax.swing.JLabel();
        btnMRutasGanacias = new javax.swing.JRadioButton();
        btnMBatallas = new javax.swing.JRadioButton();
        btnMRutaHorasNav = new javax.swing.JRadioButton();
        btnTRutasXY = new javax.swing.JRadioButton();
        btnRecorrerTodo = new javax.swing.JRadioButton();
        btnRmasCorta = new javax.swing.JRadioButton();
        btnRmasCostosa = new javax.swing.JRadioButton();
        btnAceptar = new javax.swing.JButton();

        jRadioButton7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Mejor Ruta Ganancias");
        jRadioButton7.setToolTipText("-\tmejor ruta para obtener más ganancias(“Tesoros”) a menor costo(“Horas”).");
        jRadioButton7.setContentAreaFilled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione Modo de Simulacion");

        buttonGroup1.add(btnMRutasGanacias);
        btnMRutasGanacias.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnMRutasGanacias.setForeground(new java.awt.Color(255, 255, 255));
        btnMRutasGanacias.setText("Mejor Ruta Ganancias");
        btnMRutasGanacias.setToolTipText("Mejor ruta para obtener más ganancias(“Tesoros”) a menor costo(“Horas”).");
        btnMRutasGanacias.setContentAreaFilled(false);

        buttonGroup1.add(btnMBatallas);
        btnMBatallas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnMBatallas.setForeground(new java.awt.Color(255, 255, 255));
        btnMBatallas.setText("Ruta con más Batallas");
        btnMBatallas.setToolTipText("Encontrar la ruta con más batallas entre X y Y.");
        btnMBatallas.setContentAreaFilled(false);

        buttonGroup1.add(btnMRutaHorasNav);
        btnMRutaHorasNav.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnMRutaHorasNav.setForeground(new java.awt.Color(255, 255, 255));
        btnMRutaHorasNav.setText("Mejor Ruta Horas Navegacion");
        btnMRutaHorasNav.setToolTipText("La mejor ruta (“Horas de navegación”) para ir de isla X a la isla Y.");
        btnMRutaHorasNav.setContentAreaFilled(false);

        buttonGroup1.add(btnTRutasXY);
        btnTRutasXY.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnTRutasXY.setForeground(new java.awt.Color(255, 255, 255));
        btnTRutasXY.setText("Todas las Rutas de X a Y");
        btnTRutasXY.setToolTipText("Encontrar todas las posibles rutas para ir de X a Y.");
        btnTRutasXY.setContentAreaFilled(false);

        buttonGroup1.add(btnRecorrerTodo);
        btnRecorrerTodo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRecorrerTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnRecorrerTodo.setText("Recorrer Todo el mapa");
        btnRecorrerTodo.setToolTipText("Encontrar la primera opción para recorrer todo el mapa");
        btnRecorrerTodo.setContentAreaFilled(false);

        buttonGroup1.add(btnRmasCorta);
        btnRmasCorta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRmasCorta.setForeground(new java.awt.Color(255, 255, 255));
        btnRmasCorta.setText("Ruta mas corta");
        btnRmasCorta.setToolTipText("Encontrar la ruta más corta para recorrer todo el mapa");
        btnRmasCorta.setContentAreaFilled(false);

        buttonGroup1.add(btnRmasCostosa);
        btnRmasCostosa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRmasCostosa.setForeground(new java.awt.Color(255, 255, 255));
        btnRmasCostosa.setText("Ruta más Costosa");
        btnRmasCostosa.setToolTipText("Encontrar la ruta más costosa (“Horas de navegación”) para ir de X a Y.");
        btnRmasCostosa.setContentAreaFilled(false);

        btnAceptar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVistaSeleccion1Layout = new javax.swing.GroupLayout(panelVistaSeleccion1);
        panelVistaSeleccion1.setLayout(panelVistaSeleccion1Layout);
        panelVistaSeleccion1Layout.setHorizontalGroup(
            panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaSeleccion1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRmasCorta)
                    .addGroup(panelVistaSeleccion1Layout.createSequentialGroup()
                        .addGroup(panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelVistaSeleccion1Layout.createSequentialGroup()
                                    .addComponent(btnMBatallas)
                                    .addGap(41, 41, 41))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVistaSeleccion1Layout.createSequentialGroup()
                                    .addComponent(btnMRutasGanacias)
                                    .addGap(39, 39, 39)))
                            .addGroup(panelVistaSeleccion1Layout.createSequentialGroup()
                                .addComponent(btnRmasCostosa)
                                .addGap(71, 71, 71)))
                        .addGroup(panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecorrerTodo)
                            .addComponent(btnMRutaHorasNav)
                            .addComponent(btnTRutasXY))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVistaSeleccion1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVistaSeleccion1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVistaSeleccion1Layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))))
        );
        panelVistaSeleccion1Layout.setVerticalGroup(
            panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaSeleccion1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMRutasGanacias)
                    .addComponent(btnMRutaHorasNav))
                .addGap(18, 18, 18)
                .addGroup(panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMBatallas)
                    .addComponent(btnTRutasXY))
                .addGap(18, 18, 18)
                .addGroup(panelVistaSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecorrerTodo)
                    .addComponent(btnRmasCostosa))
                .addGap(18, 18, 18)
                .addComponent(btnRmasCorta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnMRutasGanacias.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVistaSeleccion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVistaSeleccion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        if (this.buttonGroup1.getSelection() != null) {
            OpcionSeleccionada();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un modo de Simulacion", "ERROR!!", JOptionPane.ERROR_MESSAGE, null);
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccionModoSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccionModoSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccionModoSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccionModoSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSeleccionModoSimulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JRadioButton btnMBatallas;
    private javax.swing.JRadioButton btnMRutaHorasNav;
    private javax.swing.JRadioButton btnMRutasGanacias;
    private javax.swing.JRadioButton btnRecorrerTodo;
    private javax.swing.JRadioButton btnRmasCorta;
    private javax.swing.JRadioButton btnRmasCostosa;
    private javax.swing.JRadioButton btnTRutasXY;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton7;
    private ModoEdicion.PanelVistaSeleccion panelVistaSeleccion1;
    // End of variables declaration//GEN-END:variables
}
