package Interfaces;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import Clases.Sonido;
/**
 * clase que funciona como lienzo para la presentación de la interfaz de inicio 
 * del proyecto
 * @author William Vasquez y Jorge Osorio
 * @version 1.0
 */
public class DibujosInicio extends javax.swing.JPanel {

    Sonido audio;
    /**
     * Constructor que instancia el panel para la interfaz de inicio, el cual trae
     * consigo una imagen y un sonido
     */
    public DibujosInicio() {
        initComponents();
        this.audio = new Sonido("../Sonidos/300Violin.wav");
        this.audio.Play();
    }

    /**
     * metodo que nos permite dibujar una imagen de fondo en el lienzo 
     * @param g instancia de la clase graphics de java
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(new ImageIcon(getClass().getResource("../Imagenes/BannerInicio.jpg")).getImage(), 0, 0, this.getSize().width, this.getSize().height, this);
        repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
