/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ModoEdicion.Serializador;
import ModoEdicion.VistaConstructor;
import ModoEdicion.VistaSeleccionModoSimulacion;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.UIManager;

/**
 *
 * @author JORGE OSORIO
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public static int opcionSimulacion;

    static {
        opcionSimulacion = 0;
    }

    public Inicio() {
        initComponents();
        this.Configuraciones();
        this.CambiarCursorBotones();

    }

    private void Configuraciones() {
        this.setTitle("PIRATAS POR EL MUNDO");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/Icono.png")).getImage());
    }

    private void CambiarCursorBotones() {
        Cursor cursor;
        ImageIcon imagenes = new ImageIcon(getClass().getResource("../Imagenes/espada.png"));
        Toolkit t = Toolkit.getDefaultToolkit();
        cursor = t.createCustomCursor(imagenes.getImage(), new Point(1, 1), "Cursor");
        this.btnCargarMapa.setCursor(cursor);
        this.btnInstrucciones.setCursor(cursor);
        this.btnComenzar.setCursor(cursor);
        this.btnModificarMapa.setCursor(cursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dibujosInicio1 = new Interfaces.DibujosInicio();
        btnCargarMapa = new javax.swing.JButton();
        btnComenzar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnModificarMapa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarMapa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCargarMapa.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarMapa.setText("CARGAR MAPA");
        btnCargarMapa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCargarMapa.setContentAreaFilled(false);
        btnCargarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarMapaActionPerformed(evt);
            }
        });

        btnComenzar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnComenzar.setForeground(new java.awt.Color(255, 255, 255));
        btnComenzar.setText("DISEÑAR MAPA");
        btnComenzar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComenzar.setContentAreaFilled(false);
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });

        btnInstrucciones.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("INSTRUCCIONES");
        btnInstrucciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInstrucciones.setContentAreaFilled(false);
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });

        jLabel1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JORGE PIEDRAHITA - WILLIAM VASQUEZ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono2x.png"))); // NOI18N
        jLabel3.setText("PIRATAS POR EL MUNDO");

        btnModificarMapa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnModificarMapa.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarMapa.setText("MODIFICAR MAPA");
        btnModificarMapa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarMapa.setContentAreaFilled(false);
        btnModificarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dibujosInicio1Layout = new javax.swing.GroupLayout(dibujosInicio1);
        dibujosInicio1.setLayout(dibujosInicio1Layout);
        dibujosInicio1Layout.setHorizontalGroup(
            dibujosInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dibujosInicio1Layout.createSequentialGroup()
                .addGroup(dibujosInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dibujosInicio1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(dibujosInicio1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(dibujosInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dibujosInicio1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(btnModificarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCargarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dibujosInicio1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        dibujosInicio1Layout.setVerticalGroup(
            dibujosInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dibujosInicio1Layout.createSequentialGroup()
                .addGroup(dibujosInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dibujosInicio1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dibujosInicio1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCargarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnModificarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(btnInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dibujosInicio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dibujosInicio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarMapaActionPerformed
        JFileChooser selectorArchivo = new JFileChooser();
        int seleccion = selectorArchivo.showDialog(this, "SELECCIONE SU MAPA");
        if (seleccion == selectorArchivo.getApproveButtonMnemonic()) {
            Serializador serializador = new Serializador();
            VistaSeleccionModoSimulacion vs = new VistaSeleccionModoSimulacion();
            vs.setVisible(true);
            Simulación simulacion = new Simulación(serializador.ReadArchivo(selectorArchivo.getSelectedFile().getPath()), opcionSimulacion);
            simulacion.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Pulso cancelar");
        }

    }//GEN-LAST:event_btnCargarMapaActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        //JOptionPane.showMessageDialog(this, "TODAVIA NO HAY INSTRUCCIONES JAJAJA", "INTRUCCIONES", JOptionPane.INFORMATION_MESSAGE, null);
        VistaSeleccionModoSimulacion vSeleccion = new VistaSeleccionModoSimulacion();
        vSeleccion.setVisible(true);
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        VistaConstructor vistC = new VistaConstructor();
        vistC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnModificarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMapaActionPerformed
        JFileChooser selectorArchivo = new JFileChooser();
        int seleccion = selectorArchivo.showDialog(this, "SELECCIONE SU MAPA");
        if (seleccion == selectorArchivo.getApproveButtonMnemonic()) {
            Serializador serializador = new Serializador();
            VistaConstructor vc = new VistaConstructor(serializador.ReadArchivo(selectorArchivo.getSelectedFile().getPath()));
            vc.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Pulso cancelar");
        }
    }//GEN-LAST:event_btnModificarMapaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
                if(opcionSimulacion!=0){
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarMapa;
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnModificarMapa;
    private Interfaces.DibujosInicio dibujosInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
